-- Intentionally empty seed.
--
-- The RELAPSE catalogue cannot be seeded yet: confirmed prices/MRP, SKUs,
-- sizes, weights and concentrations have not been supplied by the client.
-- Inventing them would fabricate business data, so this file stays a no-op
-- until real catalogue data arrives.
--
-- Demo mode does not need seeding — the storefront reads data/demo-products.ts
-- when NEXT_PUBLIC_DEMO_MODE=true.
--
-- The pre-RELAPSE demo seed is archived (NON-EXECUTABLE) at
-- docs/legacy/seed-pre-relapse.sql and must never be run against any project.
