"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

export function AuthPanel() {
  const [mode,setMode]=useState<"signin"|"signup">("signin"); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(formData:FormData){setBusy(true);setMessage("");const supabase=createClient();if(!supabase){setMessage("Accounts are unavailable until Supabase public keys are configured.");setBusy(false);return;}const email=String(formData.get("email")||"");const password=String(formData.get("password")||"");const name=String(formData.get("name")||"");const result=mode==="signin"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(result.error)setMessage(result.error.message);else if(mode==="signup")setMessage("Account created. Check your email if confirmation is enabled.");else window.location.reload();setBusy(false);}
  return <div className="auth-panel"><div className="auth-copy"><p className="kicker">Your shelf</p><h1>Keep the scents<br/><em>you return to.</em></h1><p>Addresses, order history, tracking and discovery credits live here. Guest checkout always remains available.</p></div><form action={submit}><div className="auth-tabs"><button type="button" className={mode==="signin"?"active":""} onClick={()=>setMode("signin")}>Sign in</button><button type="button" className={mode==="signup"?"active":""} onClick={()=>setMode("signup")}>Create account</button></div>{mode==="signup"?<label>Name<input name="name" autoComplete="name" required/></label>:null}<label>Email<input name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" autoComplete={mode==="signin"?"current-password":"new-password"} minLength={8} required/></label>{message?<p className="form-note" role="status">{message}</p>:null}<button className="button dark-button full-button" disabled={busy}>{busy?"Working…":mode==="signin"?"Sign in":"Create account"}</button></form></div>;
}
