const copy: Record<string, string> = {
  "Black pepper": "dry heat, bright lift and a faintly mineral bite",
  Bergamot: "sparkling citrus with a bitter-green edge",
  Elemi: "lemony resin, peppered and quietly incense-like",
  Suede: "soft leather texture without the heaviness of smoke",
  Iris: "cool powder, rooty earth and polished restraint",
  Cedar: "pencil-dry wood with clean, vertical structure",
  Amber: "warm resinous glow that rounds sharp edges",
  Vetiver: "dry grass, roots and a smoky mineral finish",
  Smoke: "charred air and embers rather than sweet tobacco",
  Saffron: "metallic warmth, hay and a subtle leathery tension",
  "Pink pepper": "rosy spice that brightens without becoming hot",
  Pear: "watery fruit and a soft crystalline sweetness",
  Rose: "petal-rich floral depth, green at the edges",
  Jasmine: "radiant white petals with warm skin-like facets",
  Violet: "cool petals, powder and a faint leafy shadow",
  Vanilla: "rounded sweetness that turns creamier with warmth",
  "White musk": "clean fabric, warm skin and a soft diffusion",
  Sandalwood: "creamy wood with milky, polished depth",
  Cardamom: "cool spice, eucalyptus lift and a woody core",
  "Lemon peel": "bright zest with bitter pith underneath",
  Juniper: "gin-like freshness, pine needles and cool air",
  Cypress: "aromatic green wood with a dry, resinous line",
  Musk: "soft warmth that blurs fragrance into skin",
  Amberwood: "dry modern woods with ambery projection",
  "Dried plum": "dark fruit with tart skin and wine-like depth",
  "Toasted oak": "warm barrel wood, tannin and subtle char",
  Tobacco: "dry leaf, hay and a low amber sweetness",
  Labdanum: "dark amber resin with leathered warmth",
  "Tonka bean": "almond, hay and vanilla without frosting sweetness",
  Ginger: "clean heat, citrusy brightness and snap",
  Grapefruit: "sharp bitter citrus with energetic lift",
  "Green apple": "crisp tart fruit with watery brightness",
  "Tea leaf": "dry tannin, soft herbs and a transparent bitterness",
  "Sea salt": "mineral air and a clean saline impression",
  "Cashmere wood": "smooth pale woods with a soft musky halo",
  "Sea notes": "open salt air and cool mineral spray",
  Seawater: "wet stone, salt and the shock of cold water",
  "Mandarin orange": "juicy citrus with a soft, sunlit skin",
  "Bay leaf": "green aromatic leaf with a faint clove edge",
  Ambergris: "warm marine animalic glow, salty and skin-like",
  "Guaiac wood": "smoky tar-wood, hot and dry",
  Oakmoss: "forest floor, bitter moss and damp bark",
  Patchouli: "earthy leaves, dark chocolate depth and cool soil",
  "Jasmine bud extract": "a fresh, green and petal-rich opening",
  Tuberose: "rich, natural and creamy floral intensity",
  "Rangoon Creeper": "a South Indian flower that changes colour as it blooms — powdery, sweet and fruity at the floral edge",
  "Mysore sandalwood": "a rich, warm and creamy base note, driven by alpha-santalol and beta-santalol — long-lasting, velvety depth",
  "Creamy woods": "soft woods lined with milk and warmth",
  Whisky: "warm boozy vapours, malt and oak",
  "Sharp spice": "a peppery kick that cuts through sweetness",
  Cinnamon: "hot bark, dusty sweetness and warmth",
  Coriander: "green seed spice with a citrusy shadow",
  "Sweet vanilla": "creamier, softer vanilla without the sugar",
  "Oudh (Agarwood)": "deep resinous smoke, leathery and precious",
  "Rich leather": "supple dark leather, worn and warm",
  "Green nuances": "cut stems, fresh leaves and wet sap",
  Rosemary: "resinous pine herb with a clean bite",
  Calone: "the molecule behind open-sea air and watermelon rind",
  Neroli: "bitter orange blossom, bright and slightly soapy",
  Geranium: "rose-like leaf with a green metallic hum",
};

export function noteDescription(note: string): string {
  return copy[note] || "a distinct material in the fragrance structure, designed to change character as it warms on skin";
}
