"use client";
import { useState } from "react";
import type { Product } from "@/lib/types";
import { formatINR } from "@/lib/money";

export function AdminDashboard({ products, orders, demo }: { products: Product[]; orders: any[]; demo: boolean }) {
  const [notice,setNotice]=useState(demo?"Demo admin is read-only. Connect Supabase and assign an admin role to enable mutations.":"");
  async function toggleVariant(id:string,current:boolean){const r=await fetch("/api/admin/products",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({entity:"variant",id,patch:{is_active:!current}})});const d=await r.json();if(!r.ok){setNotice(d.error||"Update failed");return;}location.reload();}
  return <div className="admin-dashboard"><header><div><p className="kicker">Operations console</p><h1>Store control,<br/><em>without clutter.</em></h1></div><span className={`env-pill ${demo?"demo":"live"}`}>{demo?"demo mode":"connected"}</span></header>{notice?<p className="admin-notice">{notice}</p>:null}<div className="admin-metrics"><div><span>Products</span><strong>{products.filter(p=>!p.isDiscoverySet).length}</strong></div><div><span>SKUs</span><strong>{products.reduce((s,p)=>s+p.variants.length,0)}</strong></div><div><span>Orders shown</span><strong>{orders.length}</strong></div><div><span>Live fulfillment</span><strong>{process.env.NEXT_PUBLIC_FULFILLMENT_STATUS||"gated"}</strong></div></div><section className="admin-section"><div className="admin-section-title"><p className="kicker">Catalogue</p><h2>Variants & pricing</h2></div><div className="admin-table"><div className="admin-row admin-head"><span>Product / SKU</span><span>Format</span><span>Price</span><span>Provider</span><span>Status</span></div>{products.flatMap(product=>product.variants.map(variant=><div className="admin-row" key={variant.id}><span><b>{product.name}</b><small>{variant.sku}</small></span><span>{variant.label}</span><span>{formatINR(variant.pricePaise)}</span><span>{variant.preferredFulfillmentProvider||"manual"}</span><span><button disabled={demo} onClick={()=>toggleVariant(variant.id,variant.available)} className={variant.available?"status-on":"status-off"}>{variant.available?"active":"off"}</button></span></div>))}</div></section><section className="admin-section"><div className="admin-section-title"><p className="kicker">Orders</p><h2>Recent activity</h2></div>{orders.length?<div className="admin-table"><div className="admin-row admin-head"><span>Order</span><span>Customer</span><span>Total</span><span>Payment</span><span>Fulfillment</span></div>{orders.map(order=><div className="admin-row" key={order.id}><span><b>{order.public_id}</b><small>{new Date(order.created_at).toLocaleString("en-IN")}</small></span><span>{order.customer_name}<small>{order.email}</small></span><span>{formatINR(order.total_paise)}</span><span>{order.payment_status}</span><span>{order.fulfillment_status}</span></div>)}</div>:<p className="account-empty">No database orders in this environment.</p>}</section></div>;
}
