import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
const require=createRequire(import.meta.url);
const required=["package.json",".env.example","next.config.ts","open-next.config.ts","wrangler.jsonc","app/layout.tsx","app/page.tsx","app/globals.css","app/api/checkout/route.ts","lib/checkout.ts","lib/order-service.ts","lib/fulfillment/types.ts","lib/fulfillment/providers/amazon-mcf.ts","lib/fulfillment/providers/shiprocket.ts","lib/fulfillment/providers/manual.ts","supabase/migrations/0001_schema.sql","supabase/migrations/0002_nextjs_commerce.sql","ARCHITECTURE.md","DECISIONS.md","SECRETS_AND_KEYS.md","LAUNCH_CHECKLIST.md"];
let failed=false;for(const file of required)if(!fs.existsSync(file)){console.error(`Missing required file: ${file}`);failed=true;}
const env=fs.readFileSync(".env.example","utf8");for(const forbidden of [/rzp_live_[A-Za-z0-9]+/,/SUPABASE_SERVICE_ROLE_KEY=eyJ/,/amzn1\.application-oa2-client\.[A-Za-z0-9]+/])if(forbidden.test(env)){console.error("Potential live credential in sample config");failed=true;}
function walk(dir,out=[]){if(!fs.existsSync(dir))return out;for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(["node_modules",".next",".open-next"].includes(entry.name))continue;const full=path.join(dir,entry.name);if(entry.isDirectory())walk(full,out);else out.push(full);}return out;}
const codeFiles=[...walk("app"),...walk("components"),...walk("lib"),...walk("data")].filter(f=>/\.(ts|tsx)$/.test(f)&&!f.endsWith(".d.ts"));
try{const ts=require("typescript");for(const file of codeFiles){const source=fs.readFileSync(file,"utf8");const result=ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext},reportDiagnostics:true,fileName:file});const errors=(result.diagnostics||[]).filter(d=>d.category===ts.DiagnosticCategory.Error);if(errors.length){failed=true;console.error(`Syntax diagnostics in ${file}:`);for(const d of errors)console.error(ts.flattenDiagnosticMessageText(d.messageText,"\n"));}}console.log(`TypeScript syntax preflight: ${codeFiles.length} files transpiled.`);}catch(error){console.warn("TypeScript syntax preflight skipped until dependencies are installed:",error?.message||error);}
const css=walk("app").filter((file)=>file.endsWith(".css")).map((file)=>fs.readFileSync(file,"utf8")).join("\n");if(/purple|violet gradient/i.test(css)){console.error("Banned generic luxury color language found in CSS");failed=true;}if(!css.includes("prefers-reduced-motion")){console.error("Reduced-motion CSS path missing");failed=true;}
if(failed)process.exit(1);console.log("Preflight passed.");
